### ISSUE TITLE
Feature creep

### ISSUE THREAD

**Issue by RasheedAZ** [adenlall/salatok-gtk#16]
Thanks for making this beautiful app : )

Since it's called Salatok, wouldn't it be better to restrict functionality to salaah times and putting Qur'aan, Hadeeth and other features in a separate app?

**Comment by adenlall** [comment]
I was already thinking about this approach. but within the next coming releases,
Because it need much time than it sounds. but it is coming on future.

**Comment by adenlall** [comment]
So, I will open it on that time.
